config/routes.rb
Rails.application.routes.draw do

  # devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/dashboard' => "rails_admin/main#dashboard", :as => :dashboard
  get 'home/index'
  get '/reddera_way' => 'home#reddera_way'
  get '/professional_sign_up' => 'home#prof_sign_up'

  get'/card_destroy/:token_value'=>'users#card_destroy' ,:as=>'card_destroy'
  get 'corporate'=>'home#corporate'
  get '/faqs' => 'home#faqs'
  get '/safety' => 'home#safety'
  devise_for :users, :controllers => {:omniauth_callbacks => "callbacks", :registrations => "registrations",:confirmations=>"confirmations",:passwords => "passwords"}
  post '/users/:stylist_id/services/:service_id/bookings' => "bookings#create"
  devise_scope :users do
    get "sign_out", :to => "devise/sessions#destroy"
  end
  root 'home#index'
  match '/stylist/:id/:name'=> 'users#stylist_profile' , :via => [:get],:as=>'stylist'
  match '/client/:id/:name' => 'users#client_profile', :via => [:get],  :as=>'client'
  resources :gift_cards

  get '/gift_card_payment' => 'transactions#gift_card_payment'
  post '/gift_card_payment_create' => 'transactions#gift_card_payment_create'
  post '/pay_via_gift_card' => 'transactions#pay_via_gift_card',:as=>"pay_gift_card"

  resources :users do
    resources :favourite_stylist, :only=>[:index]
    resources :gift_cards ,:only=>[:create]
    post '/update_availability' ,to: 'update_availabilities#create' ,:as=>'create_updated_availabilities'
    get '/edit_updated_availabilities/:id' => 'update_availabilities#edit_updated_availabilities',:as=>'edit_updated_availabilities'
    delete '/delete_update_availability/:id' => 'update_availabilities#delete_update_availabilities',:as=>'delete_updated_availabilities'
    put 'payment_info' => 'payout_infos#payment_info'
    get 'dashboard' => 'users#dashboard'
    post 'service_list' => 'services#create_service'
    resources :services,:except=>[:create,:destroy]
    put 'destroy_service/:id' => 'services#destroy_service' ,:as=>'destroy_service'
    resources :previous_works
    resources :availabilities, :only=>[:index]
    put 'availability/update' => 'availabilities#update_availabilities'
    resources :bookings, :only=>[:update,:index,:destroy]
    post '/multiple_service_bookings' => 'bookings#multiple_bookings'
    put '/bookings/:id/reschedule' => 'bookings#reschedule',:as=>"reschedule"
    put '/bookings/:id/reschedule_stylist' => 'bookings#reschedule_stylist',:as=>'reschedule_stylist'
    put '/bookings/:id/reschedule_confirm' => 'bookings#reschedule_confirm_client',:as=>'rereschedule_confirm_client'
    put '/bookings/:id/booking_delete' => 'bookings#booking_delete',:as=>"delete"
    put '/bookings/:id/reschedule_confirm_by_stylist' => 'bookings#reschedule_confirm_by_stylist',:as=>'reschedule_confirm_by_stylist'
    resources :reviews,:only=>[:new,:create,:index]
    get 'sytist'=>'users#stylist_login'
  end

  post '/complaint/email'=>'users#complaint_email',:as=>"complaint"
  post '/inquiry/email'=>'users#inquiry_email',:as=>"inquiry"
  put '/delete_unavail_date/:date' => 'update_availabilities#delete_unavail' ,:as=>'delete_unavail'
  post '/transaction_create_testing'=>'transactions#create_transaction',:as=>'create_transaction'
  resource :service_categories,:only=>[:new,:create]
  resource :service_sub_categories,:only=>[:new,:create]
  resource :popular_services,:only=>[:new]
  put '/popular_service/:id' => 'popular_services#update',:as=>'popular_service'
  post '/users/:stylist_id/services/:service_id/reschedule_booking_client' => "bookings#reschedule_client",:as=>'reschedule_client'
  get '/service_categories/:id/service_sub_categories/:name' => 'service_categories#get_sub_categories_by_service_category' ,:as=>'service_category_sub_categories'
  post '/update_updated_availabilities/' => 'update_availabilities#update_updated_availabilities', :as=>'update_availability'
  #get 'client/:id' => 'users#client_profile',:as =>'client'
  resources :transactions, only: [:new, :create,:index,:destroy]
  post 'discounted_price'=>'transactions#discounted_price' ,:as=> 'discounted_price'
  post '/add_payment_method' => 'transactions#add_payment_method'
  post 'users/sms' => 'users#sms'
  get '/search'=> 'services#search'
  post '/sort_services'=> 'services#sort_services'
  post 'users/verify' => "users#sms_verified"
  resource :promo_codes, only: [:new,:create]
  delete '/promo_code/:id' => 'promo_codes#delete',:as=>'code_delete'
  post 'create_favourite_list' => 'favourite_stylist#create_favourite_list'
  post 'unfavourite_list' => 'favourite_stylist#unfavourite_list'

  post 'message'=> 'users#create_message'
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
  get '/featured_professionals/new' => 'featured_professionals#new'
  put '/featured_professional_update/:id' => 'featured_professionals#update',:as=>'featured_professionals_update'
  put '/recently_booked_update/:id'=>'recently_bookeds#update' ,:as=>"rec_book_update"
  get '/recently_booked/new' => 'recently_bookeds#new'
  post 'cities/:state', to: 'services#cities' ,:as=>'cities'
  get '/how_it_works'=> 'home#how_it_works',:as=>'how_it_works'
  get '/help'=> 'home#help',:as=>'help'
  get '/service_name'=>'home#service_category_name',:as=>'service_name'
  get '/inbox'=>'home#inbox',:as=>'inbox'
  resources :home do
    get :autocomplete_service_category_name, :on => :collection
  end


  namespace :api do
    namespace :v1 do
      get '/promo_codes'=>'promo_codes#index'
      get '/code_validity/:id'=>'promo_codes#code_validity'
      resources :services, only: [:index, :create, :show, :update, :destroy]
      get '/earnings'=>'bookings#earnings_for_month'
      post '/get_uuid'=>'users#get_uuid'
      post '/calc_tax'=>'transactions#calculate_tax'
      get 'favourite_stylists' => 'favourite_stylist#index'
      post '/favourite_stylist' => 'favourite_stylist#create_favourite_list'
      post '/unfavourite_stylist' => 'favourite_stylist#unfavourite_list'
      post 'users/sms' => 'users#sms'
      post 'discounted_price'=>'transactions#discounted_price' ,:as=> 'discounted_price'
      post 'users/verify' => "users#sms_verified"
      get '/users-by-service/:id' =>'services#getUsersByservice'
      post '/multiple_professionals' =>'services#getProfessionalsByMultipleSubServices'
      get 'services-by-userid/:user_id' => 'services#servicesByUserId'
      get 'service_categories/:id/sub_services'=>'services#get_sub_services_clubbed_services_f_service_category_id'
      resources :previous_works, only: [:create,:show, :update, :destroy]
      put '/users/update'=>'users#update'
      get '/user_info' => 'users#user_info'
      post '/users/update_password'=>'users#update_password'
      get 'works-by-userid/:user_id' => 'previous_works#worksByUserId'
      get '/search'=> 'services#search'
      resources :transactions, only: [:create,:index,:new]
      resources :bookings,only: [:index,:update,:create]
      put '/bookings/:id/reschedule' => 'bookings#reschedule',:as=>"reschedule"
      put '/bookings/:id/reschedule_by_stylist' => 'bookings#reschedule_stylist'
      put '/bookings/:id/reschedule_by_client' => 'bookings#reschedule_client'
      put '/bookings/:id/reschedule_confirm_client'=>'bookings#reschedule_confirm_client'
      put '/bookings/:id/reschedule_confirm_stylist'=>'bookings#reschedule_confirm_stylist'
      resources :photos,only: [:create]
      get 'services-by-userid/:user_id/sort-services'=>'services#get_sorted_services'
      post '/message_client'=> 'users#create_message_client'
      post '/message_stylist'=> 'users#create_message_stylist'
      get '/read_messages'=> 'users#read_messages'
      put 'availability/update' => 'availabilities#update_availabilities'
      resources :availabilities , only: [:index]
      resources :reviews,:only=>[:create]
      resources :gift_cards,:only=>[:create]
      resources :service_categories ,only: [:index]

      post '/pay_via_gift_card' => 'transactions#pay_via_gift_card',:as=>"pay_gift_card"
      post '/gift_card_payment_create' => 'transactions#gift_card_payment_create'
      get '/service_categories/:id/service_sub_categories' => 'service_sub_categories#get_sub_categories_by_service_category' ,:as=>'service_category_sub_categories'
      get 'reviews-by-userid/:user_id' => 'reviews#reviewsByUserId'
      resources :update_availabilities ,only:[:create]
      put '/bookings/:id/booking_delete' => 'bookings#booking_delete',:as=>"delete"
      post '/notifications_settings'=>'users#notification_settings'
      get '/notifications_settings' => 'users#get_settings_of_notifications'
      devise_scope :user do
  		  post 'registrations' => 'registrations#create', :as => 'register'
        post 'facebook-callbacks' => 'registrations#facebook',:as=>'facebook-callbacks'
        post 'google-callbacks' => 'registrations#google_oauth2',:as=>'google-callbacks'
        post 'sessions' => 'sessions#create', :as => 'login'
  		  delete 'sessions' => 'sessions#destroy', :as => 'logout'
  	  end

    end
  end

end

app/controllers/api/v1/services_controller.rb
class Api::V1::ServicesController < Api::V1::BaseController

  #skip_before_action :verify_authenticity_token
  before_action :authenticate_user!, :only => [:create, :update,:destroy,:modify_access!,:auth_to_create!]
  before_action :set_service, only: [:show, :update, :destroy,:modify_access!]
  before_action :modify_access!, :only => [:update,:destroy]
  before_action :auth_to_create!,:only=>[:create,:update,:destroy]

  def search

    services=Service.filter_services(params).paginate(:per_page => 5,:page => params[:page])
    getServicesListJson(services)
  end

  def getUsersByservice

    services=Service.getServiceByName(params)
    users=services.map(&:user)
    getUsersListJson(users)


  end

  def get_sorted_services

   user=User.find(params[:user_id])
   services=user.services.where(:is_deleted=>false).shuffle
   getServicesListJson(services)
  end

  def get_sub_services_clubbed_services_f_service_category_id
    begin
    sub_services=[]
    service_category=ServiceCategory.find(params[:id])
    services=service_category.services.select("*").joins(:service_sub_category)

    services.each{|service|sub_services.push(Api::V1::ServiceSubCategorySerializer.new(service.service_sub_category,root:false,scope:{amount:service.amount,time:service.time}))}

    #all_services=sub_services.map{|service| service.to_json}

    #jsonObj = '[{"id"":2, "name":"satendra"}]'.to_json
    render(json:{sub_services:sub_services}.to_json)
    rescue ActiveRecord::RecordNotFound
      not_found_for_services
    end    # service_category=ServiceCategory.find(params[:id])
    # services=service_category.services
    #
    #render(json:services,each_serializer: Api::V1::ServiceSubCategorySerializer)
    #


  end


  def update

    begin

      value= @service.update(service_params)
      if value==false
        render(json: { success: false, message: "Service Already exists" }.to_json)

      else
        render(json: { success: true, message: "Service updated" }.to_json)

      end



    rescue Exception => exc
      @services=current_user.services.where(:is_deleted=>false)
      render(json: { success: false, message: "Fields cannot be blank" }.to_json)




    end
  end


  def getProfessionalsByMultipleSubServices

    time_start=Availability.unix_time_convert(params[:time_start])
    time_stop=Availability.unix_time_convert(params[:time_stop])

    begin
    all_users=[]
    users=[]
    reviews=[]

    sub_services=params[:services].collect{|service_id|ServiceSubCategory.find(service_id)}
    services=sub_services.collect{|sub| sub.services.where(:is_deleted=>false)}

    services.each do |service|
       users.push(service.map(&:user).uniq)
    end

    users.collect{|user| user.map{|user| all_users.push(user)}  }
    unique_users=all_users.uniq

    filtered_u=unique_users.collect{|user| Availability.getAvailedUser(user,time_start,time_stop)==true ? user : false}.reject{|av| av==false}
    #reviews=filtered_u.map{|stylist| Review.where(:stylist_id=>stylist.id)}.map{|review| review.first}
    #favourites=filtered_u.map{|stylist| FavouriteStylist.where(:stylist_id=>stylist.id)}.map{|review| review.first}
    #session[:]="mul"

    #reviews.collect{|reviews| reviews.map{|review| reviews.push(review)}  }
    getUsersListJson(filtered_u)

    rescue ActiveRecord::RecordNotFound
      not_found
    end


  end


  def index
    services = Service.all
    getServicesListJson(services)
  end

  def show
    getServiceJson(@service)
  end

  def create
      begin

          @service=current_user.services.new(service_params)
          @service.user_id=current_user.id
          @service.save
          render(json: { status: true, message: "service created successfully" }.to_json)



        rescue Exception => exc
      # do whatever you wish to warn the user, or log something

       render(json: {  status: false, message: exc.message}.to_json)

      end
  end



  def destroy
    begin
    service=Service.find(params[:id])
    service.update(:is_deleted=>true)
    @services=current_user.services.where(:is_deleted=>false)
    render(json: { success: true, message: "Service was successfully destroyed." }.to_json)
    rescue ActiveRecord::RecordNotFound
      render(json: { success: false, message: "Record not found" }.to_json)
    end
    end

  def servicesByUserId
    begin
      services = User.find(params[:user_id]).services.where(:is_deleted=>false)
      getServicesListJson(services)
    rescue ActiveRecord::RecordNotFound
      not_found
    end
  end

  protected



  def getServicesListJson(services)

    render(json:services,each_serializer: Api::V1::ServiceSerializer,root:'services')

  end

  def getUsersListJson(users)

    render(json:users,each_serializer: Api::V1::UserSerializer,:except=>[:city,:state,:zipcode,:address],root:'users')
  end

  def getServiceJson(service)
    render(json: Api::V1::ServiceSerializer.new(service).to_json)
  end
    
  def service_params
    params.require(:service).permit(:name, :amount, :user_id,:service_category_id ,:service_sub_category_id, :time,:description,:location1,:location2,:location3,:location4,:location5)
  end

  def set_service
    begin
      @service = Service.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      not_found
    end
  end

  def auth_to_create!
    return (current_user.isStylist?) ? true : unauthenticated!
  end

  def modify_access!
    return current_user == @service.user ? true : unauthenticated!
  end

end

app/views/services/_city_list.html.erb
<div class="table-responsive table-dashboard services mselectboxmain">
  <table class="table table-condensed latest-thum-size brdn">
    <tr>
      <td>
        <div class="">
          <input id="test1" type="checkbox" name="type[]">
          <label for="test1"></label>
          <div class="LselectBox w1120 rcolor-text">
          <% if get_cities_of_new_york.blank? %>
                <select id="cities-of-state5" name="location5">
                  <option value="" selected=""></option>
                </select>
          <% else %>
              <select id="cities-of-state1" name="location1">
                <option value>Select location1</option>

                <% get_cities_of_new_york.each do |loc| %>
                    <option value=<%= loc.to_s %>><%= loc %></option>
                <% end %>
              </select>
          <% end %>
            </div>
          <div class="clearfix"></div>
        </div>
      </td>

      <td>

      <div class="">
        <input id="test2" type="checkbox" name="type[]">
        <label for="test2"></label>
        <div class="LselectBox w1120 rcolor-text">

        <% if get_cities_of_new_york.blank? %>

              <select id="cities-of-state5" name="location5">
                <option value="" selected=""></option>
              </select>

        <% else %>

              <select id="cities-of-state2" name="location2">
                <option value>Select location2</option>

                <% get_cities_of_new_york.each do |loc| %>
                    <option value=<%= loc.to_s %>><%= loc %></option>
                <% end %>
              </select>

        <% end %>
        </div>
        <div class="clearfix"></div>


      </div>
      </td>


      <td>
        <div class="">
          <input id="test3" type="checkbox" name="type[]">
          <label for="test3"></label>
          <div class="LselectBox w1120 rcolor-text">

          <% if get_cities_of_new_york.blank? %>

                <select id="cities-of-state5" name="location5">
                  <option value="" selected=""></option>
                </select>

          <% else %>

                <select id="cities-of-state3" name="location3">
                  <option value>Select location3</option>

                  <% get_cities_of_new_york.each do |loc| %>
                      <option value=<%= loc.to_s %>><%= loc %></option>
                  <% end %>
                </select>


          <% end %>

          </div>
          <div class="clearfix"></div>

        </div>
      </td>


      <td>
        <div class="">
          <input id="test4" type="checkbox" name="type[]">
          <label for="test4"></label>
          <div class="LselectBox w1120 rcolor-text">

          <% if get_cities_of_new_york.blank? %>

                <select id="cities-of-state5" name="location5">
                  <option value="" selected=""></option>
                </select>

          <% else %>

                <select id="cities-of-state4" name="location4">
                  <% get_cities_of_new_york.each do |loc| %>
                      <option value=<%= loc.to_s %>><%= loc %></option>
                  <% end %>
                </select>

          <% end %>
          </div>
          <div class="clearfix"></div>

        </div>
      </td>


      <td>

        <div class="pull-left">
          <input id="test5" type="checkbox" name="type[]">
          <label for="test5"></label>
          <div class="LselectBox w1120 rcolor-text">

          <% if get_cities_of_new_york.blank? %>
                <select id="cities-of-state5" name="location5">
                  <option value="" selected=""></option>
                </select>
          <% else %>

                <select id="cities-of-state5" name="location5">
                  <option value>Select Location5</option>
                  <% get_cities_of_new_york.each do |loc| %>
                      <option value=<%= loc.to_s %>><%= loc %></option>
                  <% end %>
                </select>
          <% end %>
          </div>


        </div>
      </td>

    </tr>
  </table>
</div>


<script>
    $('#cities-of-state1').prop('disabled',true);
    $('#cities-of-state2').prop('disabled',true);
    $('#cities-of-state3').prop('disabled',true);
    $('#cities-of-state4').prop('disabled',true);
    $('#cities-of-state5').prop('disabled',true);

    $('#test1').click(function() {
        if ($('#test1').is(":checked")){
            $('#cities-of-state1').prop('disabled',false);
        }
        else{
            $('#cities-of-state1').prop('disabled',true);
        }
    })

    $('#test2').click(function() {
        if ($('#test2').is(":checked")){
            $('#cities-of-state2').prop('disabled',false);
        }
        else{
            $('#cities-of-state2').prop('disabled',true);
        }
    })

    $('#test3').click(function() {
        if ($('#test3').is(":checked")){
            $('#cities-of-state3').prop('disabled',false);
        }
        else{
            $('#cities-of-state3').prop('disabled',true);
        }
    })

    $('#test4').click(function() {
        if ($('#test4').is(":checked")){
            $('#cities-of-state4').prop('disabled',false);
        }
        else{
            $('#cities-of-state4').prop('disabled',true);
        }
    })

    $('#test5').click(function() {
        if ($('#test5').is(":checked")){
            $('#cities-of-state5').prop('disabled',false);
        }
        else{
            $('#cities-of-state5').prop('disabled',true);
        }
    })
</script>

app/views/services/_create_service.html.erb
<% @formlist=['15', '30', '45', '60', '75', '90', '105', '120'] %>

<%= form_for :service, :url => user_service_list_path, remote: true, :html => {:method => :post} do |f| %>
    <div class="table-responsive table-dashboard services">
      <table class="table table-condensed latest-thum-size text-justfy">
        <tr>
          <div class="form-inline">
            <td>

                <%= f.text_field :name,:placeholder=>"Name", class: "form-control" %>
            </td>

            <td>


              <%= f.text_field :description,:placeholder=>"Description", class: "form-control" %>
            </td>

            <td>

              <div class="form-control">
                <%= f.select(:time, @formlist.map { |value| [value, value] }) %>
              </div>
            </td>
            <td>
                <%= f.text_field :amount,:placeholder=>"Amount", class: "form-control" %>
            </td>



            <!--  <div class="field form-group">
              <%#= f.label :image %><br>
              <input type="file" name="file" accept="image/*">
            </div>-->
            <td>

              <div class="form-group">
                <div class="actions">


                  <%= f.submit "+", class: "btn-close btn btn-small btn-primary pull-right" %>

                </div>
              </div>
            </td>

          </div>
        </tr>
      </table>
    </div>
<% end %>

app/views/services/_edit_modal.html.erb
<%if !@edit.blank?%>
    <% @formlist=['15', '30', '45', '60', '75', '90', '105', '120','135','150','165','180','195','210','225','240'] %>

    <div class="modal fade" id="edit_service_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="loginbox">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" id="closeModalLogin" data-dismiss="modal" aria-label="Close"> <span aria-hidden="true">&times;</span> </button>
          <div class="modal-body">
            <div class="col-lg-12 text-center">
              <h2 class="sh8">Login</h2>
            </div>

            <%= form_for @service, url: user_service_path(current_user.id,@service.id) ,method: :put, remote:true,:id=>"zipCodeForm" do |f| %>
                <div class="col-md-9 col-xs-12">
                  <div class="row" style="background-color: #f6f6f6cc;">
                    <div class="col-md-7 col-xs-12">
                        <div class="manage-ser-select">
                          <div class="select">
                              <%=select_tag 'service[service_category_id]', options_for_select(ServiceCategory.all.collect{ |u| [ u.name,u.id] },:selected=>@service.service_category.id),:id=>"service_categories_edit_id", :include_blank=> 'Main Category',class:"pl0",:style=>"background-color:#f6f6f6cc"%>

                              <div class="select__arrow"></div>
                         </div>

                          <div class="select">
                              <div id="sub_services_dropdown_edit">

                                <%= render :partial => "services/sub_services_dropdown", :sub_Services => {:sub_Services => @sub_services} %>

                              </div>
                          </div>
                          <div class="select"> <span aria-hidden="true" class="glyphicon glyphicon-time mr5 clock-icon"></span>
                            <%= select_tag('service[time]', options_for_select(@formlist,:selected=>@service.time.to_i.to_s),:style=>"background-color:#f6f6f6cc", class:'',:id=>"time", :include_blank=> 'Duration') %>

                            <div class="select__arrow"></div>
                          </div>

                          <div class="select"> <span aria-hidden="true" class="glyphicon fa-dollar mr5 clock-icon"></span>
                            <%= select_tag('service[amount]', options_for_select(getAmount(),:selected=>@service.amount), :style=>"background-color:#f6f6f6cc",class: '',:id=>"amount", :include_blank=> 'Price') %>

                            <div class="select__arrow"></div>
                          </div>

                     </div>
                     </div>


                    <div class="col-md-5 col-xs-12">
                      <!--<img src="<%#=asset_path('2.gif')%>" id="addLoader" class="pull-right">-->

                      <div class="location-box">
                        <div class="location-header">
                          <div class="mscls-btn">
                            <div class="row m-closebtn">
                              <div class="col-md-2">
                                <%= submit_tag "+", class: "btn-close btn btn-small btn-primary" ,:id=>"submitbtn", :stylist_id=>current_user.id,:style=>"margin-left:37px"%>
                              </div>

                            </div>

                          </div>
                          <h1>Location</h1>
                        </div>
                        <div class="ms-checkbx">
                          <%= check_box_tag "service[location1]","Manhattan",get_checked_value_location(@service.location1) %>
                          <label for="service_location1">Manhattan</label>
                        </div>
                        <div class="ms-checkbx">
                          <%= check_box_tag "service[location2]","Queens",get_checked_value_location(@service.location2) %>
                          <label for="service_location2">Queens</label>
                        </div>
                        <div class="ms-checkbx">
                          <%= check_box_tag "service[location3]","Brooklyn",get_checked_value_location(@service.location3) %>
                          <label for="service_location3">Brooklyn</label>
                        </div>
                        <div class="ms-checkbx">
                          <%= check_box_tag "service[location4]", "Bronx",get_checked_value_location(@service.location4) %>
                          <label for="service_location4">Bronx</label>
                        </div>
                        <div class="ms-checkbx">
                          <%= check_box_tag "service[location5]","Jersey City",get_checked_value_location(@service.location5)%>
                          <label for="service_location5">Jersey City</label>
                        </div>

                      </div>

                    </div>
                     </div>
                </div>

          <%end%>

                </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%end%>

<script type="text/javascript">
    $('#service_categories_edit_id').change(function () {
        var service_category=$(this).val();

        if($(this).val() == "") {



        } else {

            $.ajax({
                url: '/service_categories/'+$(this).val()+'/service_sub_categories/modal_edit_sub_service_dropdown.js',
                type: "GET"

            });
        }
    });

</script>

app/views/services/_service_list.html.erb
<%if !@message.blank?%>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%=(@message)%>
    </div>
<%end%>
<div class="row pt20">
<div class="table-responsive table-dashboard services">
    <table class="table table-condensed latest-thum-size text-justfy mzero">
    <tbody>
    <%if !@services.blank?%>
        <%@services.each do |service|%>
            <tr class="prf-offtext-services" style="background-color: #f8f8f8;">

              <td> <%=service.service_category.name%>(<%=service.service_sub_category.name%>)</td>
              <td><%=getLocationsize(service)%> Locations</td>
              <td><span class="glyphicon glyphicon-time mr5" aria-hidden="true"></span><%=service.time%></td>
              <td>$&nbsp;<%=service.amount%></td>
              <td><%=button_to "X",user_destroy_service_path(current_user,service.id),id:"destroy_service",:class=>"btn-close btn btn-small btn-primary pull-right dest-service",style:"margin-left:2px",method: :put,:remote=>true  %>
                <%=button_to "edit", edit_user_service_path(current_user,service.id),id:"edit_service",:class=>"btn-close btn btn-small btn-primary pull-right edit-service",method: :get,:remote=>true %></td>


            </tr>


    <%end%>
    <%end%>
    </tbody>
    </table>

</div>
</div>
<script>
    $('.dest-service    ').bind('ajax:beforeSend', function() {
        alert('hii')
    });


</script>

app/views/services/create_service.js.erb
$('#service_list').html(" <%= j render :partial=>"services/service_list",:locals=>{:service=>@services,:message=>@message}%>");
$('#cities_dropdown').html(" <%=j render :partial => "services/city_list", :locals => {:locations => @locations} %>");

app/views/services/modal_edit_sub_service_dropdown.js.erb
$('#sub_services_dropdown_edit').html(" <%= j render :partial => "services/sub_services_dropdown", :sub_Services => {:sub_Services => @sub_services} %>");

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>
  <p>
    <strong>Name:</strong>
    <%= @service.name %>

    <strong>Service:</strong>

    <%= image_tag @service.photo.image.url(:medium) %><br>
    <br>
    <strong>Description</strong>
    <%= @service.description %><br>
    <br>
    <strong>Amount:</strong>
    <%= @service.amount %>

  </p>
</div>

app/views/services/sort_services.js.erb
$('#searched_services').html(" <%= j render :partial=>"services/searched_services",:locals=>{:service=>@services}%>");

app/views/services/sub_service_dropdown.js.erb
$('#sub_services_dropdown').html(" <%= j render :partial => "services/sub_services_dropdown", :sub_Services => {:sub_Services => @sub_services} %>");

app/views/services/update.js.erb
$('#edit_service_modal').modal('hide')
$('#service_list').html(" <%= j render :partial=>"services/service_list",:locals=>{:service=>@services,:message=>@message}%>");