config/routes.rb
Rails.application.routes.draw do

  # devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/dashboard' => "rails_admin/main#dashboard", :as => :dashboard
  get 'home/index'
  get '/reddera_way' => 'home#reddera_way'
  get '/professional_sign_up' => 'home#prof_sign_up'

  get'/card_destroy/:token_value'=>'users#card_destroy' ,:as=>'card_destroy'
  get 'corporate'=>'home#corporate'
  get '/faqs' => 'home#faqs'
  get '/safety' => 'home#safety'
  devise_for :users, :controllers => {:omniauth_callbacks => "callbacks", :registrations => "registrations",:confirmations=>"confirmations",:passwords => "passwords"}
  post '/users/:stylist_id/services/:service_id/bookings' => "bookings#create"
  devise_scope :users do
    get "sign_out", :to => "devise/sessions#destroy"
  end
  root 'home#index'
  match '/stylist/:id/:name'=> 'users#stylist_profile' , :via => [:get],:as=>'stylist'
  match '/client/:id/:name' => 'users#client_profile', :via => [:get],  :as=>'client'
  resources :gift_cards

  get '/gift_card_payment' => 'transactions#gift_card_payment'
  post '/gift_card_payment_create' => 'transactions#gift_card_payment_create'
  post '/pay_via_gift_card' => 'transactions#pay_via_gift_card',:as=>"pay_gift_card"

  resources :users do
    resources :favourite_stylist, :only=>[:index]
    resources :gift_cards ,:only=>[:create]
    post '/update_availability' ,to: 'update_availabilities#create' ,:as=>'create_updated_availabilities'
    get '/edit_updated_availabilities/:id' => 'update_availabilities#edit_updated_availabilities',:as=>'edit_updated_availabilities'
    delete '/delete_update_availability/:id' => 'update_availabilities#delete_update_availabilities',:as=>'delete_updated_availabilities'
    put 'payment_info' => 'payout_infos#payment_info'
    get 'dashboard' => 'users#dashboard'
    post 'service_list' => 'services#create_service'
    resources :services,:except=>[:create,:destroy]
    put 'destroy_service/:id' => 'services#destroy_service' ,:as=>'destroy_service'
    resources :previous_works
    resources :availabilities, :only=>[:index]
    put 'availability/update' => 'availabilities#update_availabilities'
    resources :bookings, :only=>[:update,:index,:destroy]
    post '/multiple_service_bookings' => 'bookings#multiple_bookings'
    put '/bookings/:id/reschedule' => 'bookings#reschedule',:as=>"reschedule"
    put '/bookings/:id/reschedule_stylist' => 'bookings#reschedule_stylist',:as=>'reschedule_stylist'
    put '/bookings/:id/reschedule_confirm' => 'bookings#reschedule_confirm_client',:as=>'rereschedule_confirm_client'
    put '/bookings/:id/booking_delete' => 'bookings#booking_delete',:as=>"delete"
    put '/bookings/:id/reschedule_confirm_by_stylist' => 'bookings#reschedule_confirm_by_stylist',:as=>'reschedule_confirm_by_stylist'
    resources :reviews,:only=>[:new,:create,:index]
    get 'sytist'=>'users#stylist_login'
  end

  post '/complaint/email'=>'users#complaint_email',:as=>"complaint"
  post '/inquiry/email'=>'users#inquiry_email',:as=>"inquiry"
  put '/delete_unavail_date/:date' => 'update_availabilities#delete_unavail' ,:as=>'delete_unavail'
  post '/transaction_create_testing'=>'transactions#create_transaction',:as=>'create_transaction'
  resource :service_categories,:only=>[:new,:create]
  resource :service_sub_categories,:only=>[:new,:create]
  resource :popular_services,:only=>[:new]
  put '/popular_service/:id' => 'popular_services#update',:as=>'popular_service'
  post '/users/:stylist_id/services/:service_id/reschedule_booking_client' => "bookings#reschedule_client",:as=>'reschedule_client'
  get '/service_categories/:id/service_sub_categories/:name' => 'service_categories#get_sub_categories_by_service_category' ,:as=>'service_category_sub_categories'
  post '/update_updated_availabilities/' => 'update_availabilities#update_updated_availabilities', :as=>'update_availability'
  #get 'client/:id' => 'users#client_profile',:as =>'client'
  resources :transactions, only: [:new, :create,:index,:destroy]
  post 'discounted_price'=>'transactions#discounted_price' ,:as=> 'discounted_price'
  post '/add_payment_method' => 'transactions#add_payment_method'
  post 'users/sms' => 'users#sms'
  get '/search'=> 'services#search'
  post '/sort_services'=> 'services#sort_services'
  post 'users/verify' => "users#sms_verified"
  resource :promo_codes, only: [:new,:create]
  delete '/promo_code/:id' => 'promo_codes#delete',:as=>'code_delete'
  post 'create_favourite_list' => 'favourite_stylist#create_favourite_list'
  post 'unfavourite_list' => 'favourite_stylist#unfavourite_list'

  post 'message'=> 'users#create_message'
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
  get '/featured_professionals/new' => 'featured_professionals#new'
  put '/featured_professional_update/:id' => 'featured_professionals#update',:as=>'featured_professionals_update'
  put '/recently_booked_update/:id'=>'recently_bookeds#update' ,:as=>"rec_book_update"
  get '/recently_booked/new' => 'recently_bookeds#new'
  post 'cities/:state', to: 'services#cities' ,:as=>'cities'
  get '/how_it_works'=> 'home#how_it_works',:as=>'how_it_works'
  get '/help'=> 'home#help',:as=>'help'
  get '/service_name'=>'home#service_category_name',:as=>'service_name'
  get '/inbox'=>'home#inbox',:as=>'inbox'
  resources :home do
    get :autocomplete_service_category_name, :on => :collection
  end


  namespace :api do
    namespace :v1 do
      get '/promo_codes'=>'promo_codes#index'
      get '/code_validity/:id'=>'promo_codes#code_validity'
      resources :services, only: [:index, :create, :show, :update, :destroy]
      get '/earnings'=>'bookings#earnings_for_month'
      post '/get_uuid'=>'users#get_uuid'
      post '/calc_tax'=>'transactions#calculate_tax'
      get 'favourite_stylists' => 'favourite_stylist#index'
      post '/favourite_stylist' => 'favourite_stylist#create_favourite_list'
      post '/unfavourite_stylist' => 'favourite_stylist#unfavourite_list'
      post 'users/sms' => 'users#sms'
      post 'discounted_price'=>'transactions#discounted_price' ,:as=> 'discounted_price'
      post 'users/verify' => "users#sms_verified"
      get '/users-by-service/:id' =>'services#getUsersByservice'
      post '/multiple_professionals' =>'services#getProfessionalsByMultipleSubServices'
      get 'services-by-userid/:user_id' => 'services#servicesByUserId'
      get 'service_categories/:id/sub_services'=>'services#get_sub_services_clubbed_services_f_service_category_id'
      resources :previous_works, only: [:create,:show, :update, :destroy]
      put '/users/update'=>'users#update'
      get '/user_info' => 'users#user_info'
      post '/users/update_password'=>'users#update_password'
      get 'works-by-userid/:user_id' => 'previous_works#worksByUserId'
      get '/search'=> 'services#search'
      resources :transactions, only: [:create,:index,:new]
      resources :bookings,only: [:index,:update,:create]
      put '/bookings/:id/reschedule' => 'bookings#reschedule',:as=>"reschedule"
      put '/bookings/:id/reschedule_by_stylist' => 'bookings#reschedule_stylist'
      put '/bookings/:id/reschedule_by_client' => 'bookings#reschedule_client'
      put '/bookings/:id/reschedule_confirm_client'=>'bookings#reschedule_confirm_client'
      put '/bookings/:id/reschedule_confirm_stylist'=>'bookings#reschedule_confirm_stylist'
      resources :photos,only: [:create]
      get 'services-by-userid/:user_id/sort-services'=>'services#get_sorted_services'
      post '/message_client'=> 'users#create_message_client'
      post '/message_stylist'=> 'users#create_message_stylist'
      get '/read_messages'=> 'users#read_messages'
      put 'availability/update' => 'availabilities#update_availabilities'
      resources :availabilities , only: [:index]
      resources :reviews,:only=>[:create]
      resources :gift_cards,:only=>[:create]
      resources :service_categories ,only: [:index]

      post '/pay_via_gift_card' => 'transactions#pay_via_gift_card',:as=>"pay_gift_card"
      post '/gift_card_payment_create' => 'transactions#gift_card_payment_create'
      get '/service_categories/:id/service_sub_categories' => 'service_sub_categories#get_sub_categories_by_service_category' ,:as=>'service_category_sub_categories'
      get 'reviews-by-userid/:user_id' => 'reviews#reviewsByUserId'
      resources :update_availabilities ,only:[:create]
      put '/bookings/:id/booking_delete' => 'bookings#booking_delete',:as=>"delete"
      post '/notifications_settings'=>'users#notification_settings'
      get '/notifications_settings' => 'users#get_settings_of_notifications'
      devise_scope :user do
  		  post 'registrations' => 'registrations#create', :as => 'register'
        post 'facebook-callbacks' => 'registrations#facebook',:as=>'facebook-callbacks'
        post 'google-callbacks' => 'registrations#google_oauth2',:as=>'google-callbacks'
        post 'sessions' => 'sessions#create', :as => 'login'
  		  delete 'sessions' => 'sessions#destroy', :as => 'logout'
  	  end

    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 skip_after_filter :intercom_rails_auto_include,:only=>[:index]

  include HomeHelper
  protect_from_forgery except: :index
  #before_filter :read_notification
  #autocomplete :service_categories, :name
    def index

      if user_signed_in? && current_user.isStylist?
        redirect_to user_dashboard_path(current_user)

      else
        if  user_signed_in? && current_user.isAdmin?
          redirect_to dashboard_path
        else
        @alert = params[:alert] if !params[:alert].blank?
        @errors = params[:errors] if !params[:errors].blank?
        @confirmed = params[:confirm] if !params[:confirm].blank?
        #@services= Service.select(:name).uniq
        @availabilities = Availability::TIMEOBJ
        gon.service_names= getServiceNameList()
        @popular_services=PopularService.order(:id)
        @recently_booked=RecentlyBooked.order(:id)
        @featured_professional=FeaturedProfessional.order(:id)
       # @instagram_images = Instagram.user_recent_media("257315215").take(6)





        # voucherify = Voucherify.new({
        #                                 "applicationId" => "c70a6f00-cf91-4756-9df5-47628850002b",
        #                                 "clientSecretKey" => "3266b9f8-e246-4f79-bdf0-833929b1380c"
        #                             })
        #
        # voucherify = Voucherify.new({"applicationId" => "4a21adeb-e28e-4dde-ad58-25a8eebe5a81",
        #                              "clientSecretKey" => "228708fd-611b-4172-9456-d4d7996ab5d0"
        #                             })
        # # voucherify.publish({campaign: "Redd2", channel: "Email", customer: "swapnil.b@consultadd.com"})
        #
        # voucherify.list({ limit: 10, skip: 20})
        #
        # ua             = Urbanairship
        # client         = Urbanairship::Client.new(key:"1hDk8co4QY29YWD7tWqGnA", secret:"TbTeIR7yRT--PhwS9nyU-g")
        # debugger
        # p              = client.create_push
        # p.audience     = Urbanairship.ios_channel('979D32652E8FF943DD027E4F635ABA02B46EE47D8D2EF1DC288AC7ED8FC020F3')
        # p.notification = Urbanairship.notification(ios: Urbanairship.ios(alert: "Hello Buddy"))
        # p.device_types = Urbanairship.device_types(["ios"])
        # p.send_push
        # Urbanairship.register_device '979D32652E8FF943DD027E4F635ABA02B46EE47D8D2EF1DC288AC7ED8FC020F3'
        # notifications=[ {
        #     :aps => {:alert => 'You have a new message!', :badge => 1}
        # }]
        # Urbanairship.push notification # => true


        voucherify = Voucherify.new({:applicationId => '997c141a-537e-4697-9c1c-d0969601051b', :clientSecretKey => '912ef6bf-029a-4e9d-ab8e-b1d55927ba7e'
                                            })






        #@booking=Booking.find(session[:booking_id]) if !session[:booking_id].blank?
        end
      end
     @messages=read_messages(current_user)



    end

  def inbox
    @messages=read_messages(current_user)
    @notifications=read_notification
    respond_to do |format|
      format.js { render :file => 'layouts/inbox_js.js.erb' }
    end


  end


  def help

  end





end

app/views/home/prof_sign_up.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <div class="professional-signup">
        <div class="container">
          <div class="header-content">
            <h1 class="sh0">Join the Redd Family.</h1>
            <p class="sd0">Focus on your artistry, we’ll take care of the rest.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /.carousel -->
<section>
  <div class="container">
  <!--<div class="container">-->
    <!--<div class="row">-->
      <!--<div class="col-md-12 text-center">-->
        <!--<h2 class="reqnow-hline">Professional Sign-up</h2>-->
      <!--</div>-->
    <!--</div>-->
    <!--<div class="row">-->
      <!--<div class="form-row">-->
        <!--<div class="col-md-4">-->
          <!--<div class="form-group">-->
            <!--<label for="name"> First Name</label>-->
            <!--<input required placeholder="First Name" id="name" class="form-control" type="text">-->
          <!--</div>-->
        <!--</div>-->
        <!--<div class="col-md-4">-->
          <!--<div class="form-group">-->
            <!--<label for="name">Last Name</label>-->
            <!--<input required placeholder="Last Name" id="name" class="form-control" type="text">-->
          <!--</div>-->
        <!--</div>-->
        <!--<div class="col-md-4">-->
          <!--<div class="form-group">-->
            <!--<label for="name"> E-mail</label>-->
            <!--<input required placeholder="email" id="name" class="form-control" type="text">-->
          <!--</div>-->
        <!--</div>-->
      <!--</div>-->
      <!--<div class="form-row">-->
        <!--<div class="col-md-4">-->
          <!--<div class="form-group">-->
            <!--<label for="name"> Phone Number</label>-->
            <!--<input required placeholder="Phone Number" id="name" class="form-control" type="number">-->
          <!--</div>-->
        <!--</div>-->
        <!--<div class="col-md-4">-->
          <!--<div class="form-group">-->
            <!--<label for="name">Type of Professional</label>-->
            <!--<input required placeholder="Password" id="name" class="form-control" type="text">-->
          <!--</div>-->
        <!--</div>-->
        <!--<div class="col-md-4">-->
          <!--<div class="form-group">-->
            <!--<label for="name"> Location</label>-->
            <!--<input required placeholder="Password Confirmation" id="name" class="form-control" type="text">-->
          <!--</div>-->
        <!--</div>-->
      <!--</div>-->
      <!--<div class="form-row">-->
        <!--<div class="col-md-12 mt30">-->
          <!--<button id="btnContactUs" class="btn-confirm btn btn-small btn-primary pull-right" type="submit"> Submit</button>-->
        <!--</div>-->
      <!--</div>-->
      <!--<div class="clear"></div>-->
    <!--</div>-->


    <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>

        <div class="col-md-12">
          <h2 class="sh7">Professional Sign-up</h2>
        </div>
        <div class="col-md-12">
          <div class="row">
            <div class="form-row">
              <div class="col-md-4">
                <div class="form-group">
                  <label for="name"> First Name</label>
                  <%= f.text_field :first_name, autofocus: true, class: "form-control" ,:placeholder=>"First Name",:required=>true%>
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                  <label for="name">Last Name</label>
                  <%= f.text_field :last_name, autofocus: true, class: "form-control",:placeholder=>"Last Name",:required=>true %>
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                  <label for="name"> E-mail</label>
                  <%= f.email_field :email, autofocus: true, class: "form-control" ,:placeholder=>"Email",:required=>true %>
                </div>
              </div>
            </div>
            <div class="form-row">
              <div class="col-md-4">
                <div class="form-group">
                  <label for="name"> Phone Number</label>
                  <%= f.text_field :phone, :placeholder=>"Phone",class: "form-control" , autocomplete: "off",:required=>true  %> </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label for="name">Password</label>
                <% if @minimum_password_length %>
                    <em>(<%= @minimum_password_length %> characters minimum)</em>
                <% end %><br/>
                <%= f.password_field :password, autocomplete: "off", class: "form-control",:placeholder=>"Password" ,:required=>true %>                    </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label for="name"> Password Confirmation</label>
                <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control",:placeholder=>"Password Confirmation",:required=>true  %>
              </div>
            </div>

            <div class="col-md-4">
              <div class="form-group">
                <label for="name"> Type of Professional</label>
                <%= f.text_field :stylist_type, autocomplete: "off", class: "form-control",:placeholder=>"Type of Professional" ,:required=>true %>
              </div>
            </div>
          </div>
          <%= f.hidden_field :role_id, :value => Role::STYLIST %>

          <!--btn -->
          <div class="clearfix"></div>
          <div class="row mt35">

            <%- if devise_mapping.omniauthable? %>
                <%- resource_class.omniauth_providers.each do |provider| %>

                    <% if provider == :facebook %>
                        <div class="col-md-4">
                          <div class="input-group"> <span class="input-group-addon addon-facebook"> <i class="fa fa-fw fa-2x fa-facebook fa-fw"></i> </span> <a class="btn btn-lg btn-block btn-facebook" href="<%= omniauth_authorize_path(resource_name, provider,role_id:3) %>" > Sign Up with Facebook</a> </div>
                        </div>
                    <%elsif provider == :google_oauth2 %>
                        <div class="col-md-4">
                          <div class="input-group"> <span class="input-group-addon addon-google"> <i class="fa fa-fw fa-2x fa-google fa-fw"></i> </span> <a class="input-group-addon addon-google" href="<%= omniauth_authorize_path(resource_name, provider,role_id:3) %>"> Sign Up with Google</a> </div>
                        </div>

                    <%end%>
                <%end%>
            <%end%>
            <div class="col-md-4">
              <%= f.submit "Sign up", class: "btn-confirm btn btn-small btn-primary pull-right" %>
            </div>
          </div>
          <div class="clear"></div>
        </div>
        <%end%>
  </div>
</section>
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2 class="ryob-hline">Run Your Own Business</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-8 col-sm-12">
        <div class=""><img src="<%=asset_path('ps-img1.jpg')%>"> </div>
      </div>
      <div class="col-md-4 col-sm-12">
        <div class="pull-right"><img src="<%=asset_path('ps-img2.jpg')%>"> </div>
      </div>
    </div>
    <div class="row">
      <p class="ps-text">As a professional on the Reddera platform, you’ll have the freedom to create your own profile that lists your in-home and on-site services, allows clients to directly book you, and showcases your talent. We take care of all the heavy legwork so you can build your business and focus on your artistry. Your schedule is completely flexible and easily changeable with the click of a mouse.</p>
    </div>
  </div>
</section>
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-xs-12 text-center">
        <h2 class="rofb-h1">Reddera Offers Beauty and Wellness Professionals</h2>
      </div>
    </div>
    <div class="col-md-4 col-xs-12 text-center">
      <div class="corporate-off">
        <figure data-wow-delay=".1s" class="wow bounceIn text-primary" style="visibility: visible; animation-delay: 0.1s; animation-name: bounceIn;"><img src="<%=asset_path('ps-img3.png')%>"></figure>
        <h1>Services</h1>
        <p> Showcase your skills with a custom profile and URL, easy and flexible scheduling, photos and much more! </p>
      </div>
    </div>
    <div class="col-md-4 col-xs-12 text-center">
      <div class="corporate-off">
        <figure data-wow-delay=".1s" class="wow bounceIn text-primary" style="visibility: visible; animation-delay: 0.1s; animation-name: bounceIn;"><img src="<%=asset_path('ps-img4.png')%>"></figure>
        <h1>Professionals</h1>
        <p>Clients can easily request and pay for a service directly from your profile. You receive payment after the work is done. It’s as simple as that! </p>
      </div>
    </div>
    <div class="col-md-4 col-xs-12 text-center">
      <div class="corporate-off">
        <figure data-wow-delay=".1s" class="wow bounceIn text-primary" style="visibility: visible; animation-delay: 0.1s; animation-name: bounceIn;"><img src="<%=asset_path('ps-img5.png')%>"></figure>
        <h1>Safety</h1>
        <p>We provide both a customer helpline and a support system for professionals to handle any issues or disputes. </p>
      </div>
    </div>
  </div>
</section>
<div class="text-center mt35">
  <button type="submit" class="btn-confirm btn btn-small btn-primary p-all" id="btnContactUs"> Join Now</button>
</div>
<br/>
<!--<section>-->
  <!--<div class="container">-->
    <!--<div class="row">-->
      <!--<div class="col-md-12 col-xs-12 text-center">-->
        <!--<h2 class="rofb-h1">Reddera Offers Beauty and Wellness Professionals</h2>-->
      <!--</div>-->
    <!--</div>-->
    <!--<div class="col-md-4 col-xs-12 text-center">-->
      <!--<div class="corporate-off">-->
        <!--<figure data-wow-delay=".1s" class="wow bounceIn text-primary" style="visibility: visible; animation-delay: 0.1s; animation-name: bounceIn;"><img src="<%#=asset_path('ps-img3.png')%>"></figure>-->
        <!--<h1>Services</h1>-->
        <!--<p> Showcase your skills with a custom profile and URL, easy and flexible scheduling, photos and much more! </p>-->
      <!--</div>-->
    <!--</div>-->
    <!--<div class="col-md-4 col-xs-12 text-center">-->
      <!--<div class="corporate-off">-->
        <!--<figure data-wow-delay=".1s" class="wow bounceIn text-primary" style="visibility: visible; animation-delay: 0.1s; animation-name: bounceIn;"><img src="<%#=asset_path('ps-img4.png')%>"></figure>-->
        <!--<h1>Professionals</h1>-->
        <!--<p>Clients can easily request and pay for a service directly from your profile. You receive payment after the work is done. It’s as simple as that! </p>-->
      <!--</div>-->
    <!--</div>-->
    <!--<div class="col-md-4 col-xs-12 text-center">-->
      <!--<div class="corporate-off">-->
        <!--<figure data-wow-delay=".1s" class="wow bounceIn text-primary" style="visibility: visible; animation-delay: 0.1s; animation-name: bounceIn;"><img src="<%#=asset_path('ps-img5.png')%>"></figure>-->
        <!--<h1>Safety</h1>-->
        <!--<p>We provide both a customer helpline and a support system for professionals to handle any issues or disputes. </p>-->
      <!--</div>-->
    <!--</div>-->



  <!--</div>-->
<!--</section>-->