config/routes.rb
Rails.application.routes.draw do

  # devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/dashboard' => "rails_admin/main#dashboard", :as => :dashboard
  get 'home/index'
  get '/reddera_way' => 'home#reddera_way'
  get '/professional_sign_up' => 'home#prof_sign_up'

  get'/card_destroy/:token_value'=>'users#card_destroy' ,:as=>'card_destroy'
  get 'corporate'=>'home#corporate'
  get '/faqs' => 'home#faqs'
  get '/safety' => 'home#safety'
  devise_for :users, :controllers => {:omniauth_callbacks => "callbacks", :registrations => "registrations",:confirmations=>"confirmations",:passwords => "passwords"}
  post '/users/:stylist_id/services/:service_id/bookings' => "bookings#create"
  devise_scope :users do
    get "sign_out", :to => "devise/sessions#destroy"
  end
  root 'home#index'
  match '/stylist/:id/:name'=> 'users#stylist_profile' , :via => [:get],:as=>'stylist'
  match '/client/:id/:name' => 'users#client_profile', :via => [:get],  :as=>'client'
  resources :gift_cards

  get '/gift_card_payment' => 'transactions#gift_card_payment'
  post '/gift_card_payment_create' => 'transactions#gift_card_payment_create'
  post '/pay_via_gift_card' => 'transactions#pay_via_gift_card',:as=>"pay_gift_card"

  resources :users do
    resources :favourite_stylist, :only=>[:index]
    resources :gift_cards ,:only=>[:create]
    post '/update_availability' ,to: 'update_availabilities#create' ,:as=>'create_updated_availabilities'
    get '/edit_updated_availabilities/:id' => 'update_availabilities#edit_updated_availabilities',:as=>'edit_updated_availabilities'
    delete '/delete_update_availability/:id' => 'update_availabilities#delete_update_availabilities',:as=>'delete_updated_availabilities'
    put 'payment_info' => 'payout_infos#payment_info'
    get 'dashboard' => 'users#dashboard'
    post 'service_list' => 'services#create_service'
    resources :services,:except=>[:create,:destroy]
    put 'destroy_service/:id' => 'services#destroy_service' ,:as=>'destroy_service'
    resources :previous_works
    resources :availabilities, :only=>[:index]
    put 'availability/update' => 'availabilities#update_availabilities'
    resources :bookings, :only=>[:update,:index,:destroy]
    post '/multiple_service_bookings' => 'bookings#multiple_bookings'
    put '/bookings/:id/reschedule' => 'bookings#reschedule',:as=>"reschedule"
    put '/bookings/:id/reschedule_stylist' => 'bookings#reschedule_stylist',:as=>'reschedule_stylist'
    put '/bookings/:id/reschedule_confirm' => 'bookings#reschedule_confirm_client',:as=>'rereschedule_confirm_client'
    put '/bookings/:id/booking_delete' => 'bookings#booking_delete',:as=>"delete"
    put '/bookings/:id/reschedule_confirm_by_stylist' => 'bookings#reschedule_confirm_by_stylist',:as=>'reschedule_confirm_by_stylist'
    resources :reviews,:only=>[:new,:create,:index]
    get 'sytist'=>'users#stylist_login'
  end

  post '/complaint/email'=>'users#complaint_email',:as=>"complaint"
  post '/inquiry/email'=>'users#inquiry_email',:as=>"inquiry"
  put '/delete_unavail_date/:date' => 'update_availabilities#delete_unavail' ,:as=>'delete_unavail'
  post '/transaction_create_testing'=>'transactions#create_transaction',:as=>'create_transaction'
  resource :service_categories,:only=>[:new,:create]
  resource :service_sub_categories,:only=>[:new,:create]
  resource :popular_services,:only=>[:new]
  put '/popular_service/:id' => 'popular_services#update',:as=>'popular_service'
  post '/users/:stylist_id/services/:service_id/reschedule_booking_client' => "bookings#reschedule_client",:as=>'reschedule_client'
  get '/service_categories/:id/service_sub_categories/:name' => 'service_categories#get_sub_categories_by_service_category' ,:as=>'service_category_sub_categories'
  post '/update_updated_availabilities/' => 'update_availabilities#update_updated_availabilities', :as=>'update_availability'
  #get 'client/:id' => 'users#client_profile',:as =>'client'
  resources :transactions, only: [:new, :create,:index,:destroy]
  post 'discounted_price'=>'transactions#discounted_price' ,:as=> 'discounted_price'
  post '/add_payment_method' => 'transactions#add_payment_method'
  post 'users/sms' => 'users#sms'
  get '/search'=> 'services#search'
  post '/sort_services'=> 'services#sort_services'
  post 'users/verify' => "users#sms_verified"
  resource :promo_codes, only: [:new,:create]
  delete '/promo_code/:id' => 'promo_codes#delete',:as=>'code_delete'
  post 'create_favourite_list' => 'favourite_stylist#create_favourite_list'
  post 'unfavourite_list' => 'favourite_stylist#unfavourite_list'

  post 'message'=> 'users#create_message'
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
  get '/featured_professionals/new' => 'featured_professionals#new'
  put '/featured_professional_update/:id' => 'featured_professionals#update',:as=>'featured_professionals_update'
  put '/recently_booked_update/:id'=>'recently_bookeds#update' ,:as=>"rec_book_update"
  get '/recently_booked/new' => 'recently_bookeds#new'
  post 'cities/:state', to: 'services#cities' ,:as=>'cities'
  get '/how_it_works'=> 'home#how_it_works',:as=>'how_it_works'
  get '/help'=> 'home#help',:as=>'help'
  get '/service_name'=>'home#service_category_name',:as=>'service_name'
  get '/inbox'=>'home#inbox',:as=>'inbox'
  resources :home do
    get :autocomplete_service_category_name, :on => :collection
  end


  namespace :api do
    namespace :v1 do
      get '/promo_codes'=>'promo_codes#index'
      get '/code_validity/:id'=>'promo_codes#code_validity'
      resources :services, only: [:index, :create, :show, :update, :destroy]
      get '/earnings'=>'bookings#earnings_for_month'
      post '/get_uuid'=>'users#get_uuid'
      post '/calc_tax'=>'transactions#calculate_tax'
      get 'favourite_stylists' => 'favourite_stylist#index'
      post '/favourite_stylist' => 'favourite_stylist#create_favourite_list'
      post '/unfavourite_stylist' => 'favourite_stylist#unfavourite_list'
      post 'users/sms' => 'users#sms'
      post 'discounted_price'=>'transactions#discounted_price' ,:as=> 'discounted_price'
      post 'users/verify' => "users#sms_verified"
      get '/users-by-service/:id' =>'services#getUsersByservice'
      post '/multiple_professionals' =>'services#getProfessionalsByMultipleSubServices'
      get 'services-by-userid/:user_id' => 'services#servicesByUserId'
      get 'service_categories/:id/sub_services'=>'services#get_sub_services_clubbed_services_f_service_category_id'
      resources :previous_works, only: [:create,:show, :update, :destroy]
      put '/users/update'=>'users#update'
      get '/user_info' => 'users#user_info'
      post '/users/update_password'=>'users#update_password'
      get 'works-by-userid/:user_id' => 'previous_works#worksByUserId'
      get '/search'=> 'services#search'
      resources :transactions, only: [:create,:index,:new]
      resources :bookings,only: [:index,:update,:create]
      put '/bookings/:id/reschedule' => 'bookings#reschedule',:as=>"reschedule"
      put '/bookings/:id/reschedule_by_stylist' => 'bookings#reschedule_stylist'
      put '/bookings/:id/reschedule_by_client' => 'bookings#reschedule_client'
      put '/bookings/:id/reschedule_confirm_client'=>'bookings#reschedule_confirm_client'
      put '/bookings/:id/reschedule_confirm_stylist'=>'bookings#reschedule_confirm_stylist'
      resources :photos,only: [:create]
      get 'services-by-userid/:user_id/sort-services'=>'services#get_sorted_services'
      post '/message_client'=> 'users#create_message_client'
      post '/message_stylist'=> 'users#create_message_stylist'
      get '/read_messages'=> 'users#read_messages'
      put 'availability/update' => 'availabilities#update_availabilities'
      resources :availabilities , only: [:index]
      resources :reviews,:only=>[:create]
      resources :gift_cards,:only=>[:create]
      resources :service_categories ,only: [:index]

      post '/pay_via_gift_card' => 'transactions#pay_via_gift_card',:as=>"pay_gift_card"
      post '/gift_card_payment_create' => 'transactions#gift_card_payment_create'
      get '/service_categories/:id/service_sub_categories' => 'service_sub_categories#get_sub_categories_by_service_category' ,:as=>'service_category_sub_categories'
      get 'reviews-by-userid/:user_id' => 'reviews#reviewsByUserId'
      resources :update_availabilities ,only:[:create]
      put '/bookings/:id/booking_delete' => 'bookings#booking_delete',:as=>"delete"
      post '/notifications_settings'=>'users#notification_settings'
      get '/notifications_settings' => 'users#get_settings_of_notifications'
      devise_scope :user do
  		  post 'registrations' => 'registrations#create', :as => 'register'
        post 'facebook-callbacks' => 'registrations#facebook',:as=>'facebook-callbacks'
        post 'google-callbacks' => 'registrations#google_oauth2',:as=>'google-callbacks'
        post 'sessions' => 'sessions#create', :as => 'login'
  		  delete 'sessions' => 'sessions#destroy', :as => 'logout'
  	  end

    end
  end

end

app/models/previous_work.rb
class PreviousWork < ActiveRecord::Base
  belongs_to :user

  has_one :photo, :as => :imageable ,:dependent => :destroy

  after_create :attach_default_image

  def attach_default_image
    Photo.create(:imageable_type=>self.class,:imageable_id=>self.id)
  end
end

app/controllers/api/v1/previous_works_controller.rb
class Api::V1::PreviousWorksController < Api::V1::BaseController

  before_action :authenticate_user!, :only => [:create,:show, :update,:destroy,:modify_access!,:auth_to_create!]
  before_action :set_previous_work, only: [:show, :update, :destroy,:modify_access!]
  before_action :modify_access!, :only => [ :update,:destroy]
  before_action :auth_to_create!,:only=>[:create ,:update,:destroy]

  def show
    getPreviousWorksJson(@previous_work)
  end

  def create
    previous_work =current_user.previous_works.new(previous_work_params)

    if previous_work.save
      getPreviousWorksJson(previous_work)
    else
      render(json: { status: :unprocessable_entity, message: previous_work.errors })
    end
  end

  def update
    if @previous_work.update(previous_work_params)
      getPreviousWorksJson(@previous_work)
    else
      render(json: { status: :unprocessable_entity, message:@previous_work.errors })
    end
  end

  def destroy
    @previous_work.destroy
    render(json:{ message: 'Work was successfully destroyed.' }.to_json)
  end

  def worksByUserId
    begin
      works = User.find(params[:user_id]).previous_works
      getPreviousWorksListJson(works)
    rescue ActiveRecord::RecordNotFound
      not_found
    end
  end

  protected

  def getPreviousWorksListJson(previous_works)
	  render(
			json:previous_works,
				each_serializer: Api::V1::PreviousWorkSerializer


		)

  end

  def getPreviousWorksJson(previous_works)
    render(json: Api::V1::PreviousWorkSerializer.new(previous_works).to_json)
  end

  def auth_to_create!
    return (current_user.isStylist?) ? true : unauthenticated!
  end

  def set_previous_work
    begin
      @previous_work = PreviousWork.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      not_found
    end
  end

  def previous_work_params
    params[:previous_work].permit(:legend,:description)
  end

  def modify_access!
    return current_user == @previous_work.user ? true : unauthenticated!
  end

end

app/controllers/previous_works_controller.rb
class PreviousWorksController < ApplicationController
  skip_after_filter :intercom_rails_auto_include
  before_action :set_previous_work, only: [:show, :edit, :update, :destroy]
  before_action :modify_access!, :only=>[:edit,:show,:update,:destroy]
  before_action :auth_to_create!,:only => [:index,:create]
  def index
     @previous_works = current_user.previous_works.where(is_additional:false) if current_user.isStylist?
     @additional_photos = current_user.previous_works.where(is_additional:true) if current_user.isStylist?

  end

  def show
  end

  def new
    @previous_work = current_user.previous_works.new  if current_user.isStylist?
  end

  def edit
  end

  def create

    @previous_work = current_user.previous_works.new(previous_work_params)
    respond_to do |format|

      if @previous_work.save
        Photo.create(:image=>params[:file],:imageable_type=>@previous_work.class,:imageable_id=>@previous_work.id) if !params[:file].blank?
        format.html { redirect_to   user_previous_works_path(current_user.id), notice: 'Previous work was successfully created.' }
        format.json { render :show, status: :created, location: @previous_work }
      else
        format.html { render :new }
        format.json { render json: @previous_work.errors, status: :unprocessable_entity }
      end
    end

  end


  def update

    respond_to do |format|
      if @previous_work.update(previous_work_params)
        @previous_work.photo.update_attribute(:image,params[:file]) if !params[:file].blank?
        format.html { redirect_to  user_previous_works_path(current_user.id), notice: 'Previous work was successfully updated.' }
        format.json { render :show, status: :ok, location: @previous_work }
      else
        format.html { render :edit }
        format.json { render json: @previous_work.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @previous_work.destroy
    respond_to do |format|
      format.html { redirect_to user_previous_works_path(current_user.id), notice: 'Previous work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_previous_work
    @previous_work = PreviousWork.find(params[:id])
  end

  def modify_access!
    return current_user == @previous_work.user ? true : unauthenticated!
  end

  def auth_to_create!
    return (current_user.isStylist?) ? true : unauthenticated!
  end

  def unauthenticated!
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'UnAuthorized Access' }
    end
  end


  def previous_work_params
    params.permit(:user_id,:description)
  end
end

app/helpers/previous_works_helper.rb
module PreviousWorksHelper
  def us_states
    [
        ['Alabama', 'AL'],
        ['Alaska', 'AK'],
        ['Arizona', 'AZ'],
        ['Arkansas', 'AR'],
        ['California', 'CA'],
        ['Colorado', 'CO'],
        ['Connecticut', 'CT'],
        ['Delaware', 'DE'],
        ['District of Columbia', 'DC'],
        ['Florida', 'FL'],
        ['Georgia', 'GA'],
        ['Hawaii', 'HI'],
        ['Idaho', 'ID'],
        ['Illinois', 'IL'],
        ['Indiana', 'IN'],
        ['Iowa', 'IA'],
        ['Kansas', 'KS'],
        ['Kentucky', 'KY'],
        ['Louisiana', 'LA'],
        ['Maine', 'ME'],
        ['Maryland', 'MD'],
        ['Massachusetts', 'MA'],
        ['Michigan', 'MI'],
        ['Minnesota', 'MN'],
        ['Mississippi', 'MS'],
        ['Missouri', 'MO'],
        ['Montana', 'MT'],
        ['Nebraska', 'NE'],
        ['Nevada', 'NV'],
        ['New Hampshire', 'NH'],
        ['New Jersey', 'NJ'],
        ['New Mexico', 'NM'],
        ['New York', 'NY'],
        ['North Carolina', 'NC'],
        ['North Dakota', 'ND'],
        ['Ohio', 'OH'],
        ['Oklahoma', 'OK'],
        ['Oregon', 'OR'],
        ['Pennsylvania', 'PA'],
        ['Puerto Rico', 'PR'],
        ['Rhode Island', 'RI'],
        ['South Carolina', 'SC'],
        ['South Dakota', 'SD'],
        ['Tennessee', 'TN'],
        ['Texas', 'TX'],
        ['Utah', 'UT'],
        ['Vermont', 'VT'],
        ['Virginia', 'VA'],
        ['Washington', 'WA'],
        ['West Virginia', 'WV'],
        ['Wisconsin', 'WI'],
        ['Wyoming', 'WY']
    ]
  end

  def get_photos_by_previous_works(previous_works)
    return previous_works.collect{|prev| prev.photo.image.url}
  end

  def get_previous_works(previous_works)

    return ActiveModel::ArraySerializer.new(previous_works, each_serializer: Api::V1::PreviousWorkSerializer)


  end
end

app/views/previous_works/_form.html.erb
<%= form_for ([@previous_work.user, @previous_work]), html: {multipart: true} do |f| %>
    <% if @previous_work.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@previous_work.errors.count, "error") %> prohibited this previous_work from being
            saved:</h2>

          <ul>
            <% @previous_work.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="row form-group">
      <div class="col-xs-4">
        <%= f.label "Legend" %>
        <%= f.text_field :legend, class: "form-control" %>
      </div>
    </div>
    <div class="row form-group">
      <div class="col-xs-4">
        <%= f.label "Description" %>
        <%= f.text_field :description, class: "form-control" %>
      </div>
    </div>
    <div class="field form-group">
      <%= f.label :image %><br>
      <input type="file" name="file" accept="image/*">
    </div>
    <div class="row form-group">
      <div class="actions">
        <%= f.submit "Save", class: "btn btn-success request-button", style: "height:40px;width:100px;margin-left:5%" %>
      </div>
    </div>
<% end %>

app/views/previous_works/edit.html.erb
<div class="container">
<h1>Editing Previous Work</h1>

  <%= render 'form' %>
</div>

app/views/previous_works/index.html.erb
<div class="tab-pane active" id="manageportfolio">
  <section class="container">
    <div class="row dashboard">
        <div>
          <div class="col-md-3 col-sm-3 col-xs-12">
            <div class="page-header">
              <h1 class="pull-left">Top 5 </h1>
              <span class="pull-left msg-notf-icon"><img src='<%=asset_path('icon-shedule.png')%>'></span>
              <div class="clearfix"></div>
              <h5>Edit Top 5 Portfolio Photos </h5>
            </div>
          </div>

          <div class="col-md-9 col-sm-9 col-xs-12">
            <div >

              <%if !@previous_works.blank?%>
                  <%@previous_works.each do |prev|%>
                    <div class="portfolio-box">


                          <%=image_tag prev.photo.image.url%>
                          <%= form_tag( user_previous_work_path(current_user,prev.id), :method => :put,:multipart => true )  do %>
                                <%= file_field_tag 'file',:accept=>"image/*", :onchange=>"this.form.submit();" ,:style=>"font-size:73%"%>

                          <% end %>


                  </div>

                  <%end%>
                  <div class="clearfix"></div>
              <%end%>



            </div>
            <div class="clearfix"></div>
            <hr/>
          </div>
        </div>
    </div>
    <div class="row dashboard">
        <div>
          <div class="col-md-3 col-sm-3 col-xs-12">
            <div class="page-header">
              <h1 class="pull-left">
                Additional
                <br>
                Photos
              </h1>
             <span class="pull-left msg-notf-icon">
                <img src="<%=asset_path('icon-sheduleplus.png')%>">
              </span>
              <div class="clearfix"></div>
              <h5>
                Edit or Upload Additional
                <br>
                Portfolio Photos
              </h5>

            </div>
          </div>
          <div class="col-md-9 col-sm-9 col-xs-12">
            <div>
              <%if !@additional_photos.blank?%>
                  <%@additional_photos.each do |prev|%>
                      <div class="portfolio-box">


                        <%=image_tag prev.photo.image.url%>
                        <%= form_tag( user_previous_work_path(current_user,prev.id), :method => :put,:multipart => true )  do %>
                            <%= file_field_tag 'file',:accept=>"image/*", :onchange=>"this.form.submit();" ,:style=>"font-size:73%"%>

                        <% end %>


                      </div>

                  <%end%>
                  <div class="clearfix"></div>
              <%end%>

            </div>
        </div>
        </div>
 </div>
  </section>
</div>
<script>
    $( document ).ready(function() {
        NProgress.done();

    });
        </script>

app/views/previous_works/new.html.erb
<div class="container">
<h1>New Previous Work</h1>

<%= render 'form' %>

</div>

app/views/previous_works/show.html.erb
<p id="notice"><%= notice %></p>

    <%= @previous_work.user.name %>
    <%= @previous_work.user.role.name %>
    <%= @previous_work.user.email %>
    <%= @previous_work.description    %>
<strong>Previous Work:</strong>
<%= image_tag @previous_work.photo.image.url(:medium)  %><br>
<br>
    <%= link_to 'Edit', edit_previous_work_path(@previous_work) %> <br >