config/routes.rb
Rails.application.routes.draw do

  # devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/dashboard' => "rails_admin/main#dashboard", :as => :dashboard
  get 'home/index'
  get '/reddera_way' => 'home#reddera_way'
  get '/professional_sign_up' => 'home#prof_sign_up'

  get'/card_destroy/:token_value'=>'users#card_destroy' ,:as=>'card_destroy'
  get 'corporate'=>'home#corporate'
  get '/faqs' => 'home#faqs'
  get '/safety' => 'home#safety'
  devise_for :users, :controllers => {:omniauth_callbacks => "callbacks", :registrations => "registrations",:confirmations=>"confirmations",:passwords => "passwords"}
  post '/users/:stylist_id/services/:service_id/bookings' => "bookings#create"
  devise_scope :users do
    get "sign_out", :to => "devise/sessions#destroy"
  end
  root 'home#index'
  match '/stylist/:id/:name'=> 'users#stylist_profile' , :via => [:get],:as=>'stylist'
  match '/client/:id/:name' => 'users#client_profile', :via => [:get],  :as=>'client'
  resources :gift_cards

  get '/gift_card_payment' => 'transactions#gift_card_payment'
  post '/gift_card_payment_create' => 'transactions#gift_card_payment_create'
  post '/pay_via_gift_card' => 'transactions#pay_via_gift_card',:as=>"pay_gift_card"

  resources :users do
    resources :favourite_stylist, :only=>[:index]
    resources :gift_cards ,:only=>[:create]
    post '/update_availability' ,to: 'update_availabilities#create' ,:as=>'create_updated_availabilities'
    get '/edit_updated_availabilities/:id' => 'update_availabilities#edit_updated_availabilities',:as=>'edit_updated_availabilities'
    delete '/delete_update_availability/:id' => 'update_availabilities#delete_update_availabilities',:as=>'delete_updated_availabilities'
    put 'payment_info' => 'payout_infos#payment_info'
    get 'dashboard' => 'users#dashboard'
    post 'service_list' => 'services#create_service'
    resources :services,:except=>[:create,:destroy]
    put 'destroy_service/:id' => 'services#destroy_service' ,:as=>'destroy_service'
    resources :previous_works
    resources :availabilities, :only=>[:index]
    put 'availability/update' => 'availabilities#update_availabilities'
    resources :bookings, :only=>[:update,:index,:destroy]
    post '/multiple_service_bookings' => 'bookings#multiple_bookings'
    put '/bookings/:id/reschedule' => 'bookings#reschedule',:as=>"reschedule"
    put '/bookings/:id/reschedule_stylist' => 'bookings#reschedule_stylist',:as=>'reschedule_stylist'
    put '/bookings/:id/reschedule_confirm' => 'bookings#reschedule_confirm_client',:as=>'rereschedule_confirm_client'
    put '/bookings/:id/booking_delete' => 'bookings#booking_delete',:as=>"delete"
    put '/bookings/:id/reschedule_confirm_by_stylist' => 'bookings#reschedule_confirm_by_stylist',:as=>'reschedule_confirm_by_stylist'
    resources :reviews,:only=>[:new,:create,:index]
    get 'sytist'=>'users#stylist_login'
  end

  post '/complaint/email'=>'users#complaint_email',:as=>"complaint"
  post '/inquiry/email'=>'users#inquiry_email',:as=>"inquiry"
  put '/delete_unavail_date/:date' => 'update_availabilities#delete_unavail' ,:as=>'delete_unavail'
  post '/transaction_create_testing'=>'transactions#create_transaction',:as=>'create_transaction'
  resource :service_categories,:only=>[:new,:create]
  resource :service_sub_categories,:only=>[:new,:create]
  resource :popular_services,:only=>[:new]
  put '/popular_service/:id' => 'popular_services#update',:as=>'popular_service'
  post '/users/:stylist_id/services/:service_id/reschedule_booking_client' => "bookings#reschedule_client",:as=>'reschedule_client'
  get '/service_categories/:id/service_sub_categories/:name' => 'service_categories#get_sub_categories_by_service_category' ,:as=>'service_category_sub_categories'
  post '/update_updated_availabilities/' => 'update_availabilities#update_updated_availabilities', :as=>'update_availability'
  #get 'client/:id' => 'users#client_profile',:as =>'client'
  resources :transactions, only: [:new, :create,:index,:destroy]
  post 'discounted_price'=>'transactions#discounted_price' ,:as=> 'discounted_price'
  post '/add_payment_method' => 'transactions#add_payment_method'
  post 'users/sms' => 'users#sms'
  get '/search'=> 'services#search'
  post '/sort_services'=> 'services#sort_services'
  post 'users/verify' => "users#sms_verified"
  resource :promo_codes, only: [:new,:create]
  delete '/promo_code/:id' => 'promo_codes#delete',:as=>'code_delete'
  post 'create_favourite_list' => 'favourite_stylist#create_favourite_list'
  post 'unfavourite_list' => 'favourite_stylist#unfavourite_list'

  post 'message'=> 'users#create_message'
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
  get '/featured_professionals/new' => 'featured_professionals#new'
  put '/featured_professional_update/:id' => 'featured_professionals#update',:as=>'featured_professionals_update'
  put '/recently_booked_update/:id'=>'recently_bookeds#update' ,:as=>"rec_book_update"
  get '/recently_booked/new' => 'recently_bookeds#new'
  post 'cities/:state', to: 'services#cities' ,:as=>'cities'
  get '/how_it_works'=> 'home#how_it_works',:as=>'how_it_works'
  get '/help'=> 'home#help',:as=>'help'
  get '/service_name'=>'home#service_category_name',:as=>'service_name'
  get '/inbox'=>'home#inbox',:as=>'inbox'
  resources :home do
    get :autocomplete_service_category_name, :on => :collection
  end


  namespace :api do
    namespace :v1 do
      get '/promo_codes'=>'promo_codes#index'
      get '/code_validity/:id'=>'promo_codes#code_validity'
      resources :services, only: [:index, :create, :show, :update, :destroy]
      get '/earnings'=>'bookings#earnings_for_month'
      post '/get_uuid'=>'users#get_uuid'
      post '/calc_tax'=>'transactions#calculate_tax'
      get 'favourite_stylists' => 'favourite_stylist#index'
      post '/favourite_stylist' => 'favourite_stylist#create_favourite_list'
      post '/unfavourite_stylist' => 'favourite_stylist#unfavourite_list'
      post 'users/sms' => 'users#sms'
      post 'discounted_price'=>'transactions#discounted_price' ,:as=> 'discounted_price'
      post 'users/verify' => "users#sms_verified"
      get '/users-by-service/:id' =>'services#getUsersByservice'
      post '/multiple_professionals' =>'services#getProfessionalsByMultipleSubServices'
      get 'services-by-userid/:user_id' => 'services#servicesByUserId'
      get 'service_categories/:id/sub_services'=>'services#get_sub_services_clubbed_services_f_service_category_id'
      resources :previous_works, only: [:create,:show, :update, :destroy]
      put '/users/update'=>'users#update'
      get '/user_info' => 'users#user_info'
      post '/users/update_password'=>'users#update_password'
      get 'works-by-userid/:user_id' => 'previous_works#worksByUserId'
      get '/search'=> 'services#search'
      resources :transactions, only: [:create,:index,:new]
      resources :bookings,only: [:index,:update,:create]
      put '/bookings/:id/reschedule' => 'bookings#reschedule',:as=>"reschedule"
      put '/bookings/:id/reschedule_by_stylist' => 'bookings#reschedule_stylist'
      put '/bookings/:id/reschedule_by_client' => 'bookings#reschedule_client'
      put '/bookings/:id/reschedule_confirm_client'=>'bookings#reschedule_confirm_client'
      put '/bookings/:id/reschedule_confirm_stylist'=>'bookings#reschedule_confirm_stylist'
      resources :photos,only: [:create]
      get 'services-by-userid/:user_id/sort-services'=>'services#get_sorted_services'
      post '/message_client'=> 'users#create_message_client'
      post '/message_stylist'=> 'users#create_message_stylist'
      get '/read_messages'=> 'users#read_messages'
      put 'availability/update' => 'availabilities#update_availabilities'
      resources :availabilities , only: [:index]
      resources :reviews,:only=>[:create]
      resources :gift_cards,:only=>[:create]
      resources :service_categories ,only: [:index]

      post '/pay_via_gift_card' => 'transactions#pay_via_gift_card',:as=>"pay_gift_card"
      post '/gift_card_payment_create' => 'transactions#gift_card_payment_create'
      get '/service_categories/:id/service_sub_categories' => 'service_sub_categories#get_sub_categories_by_service_category' ,:as=>'service_category_sub_categories'
      get 'reviews-by-userid/:user_id' => 'reviews#reviewsByUserId'
      resources :update_availabilities ,only:[:create]
      put '/bookings/:id/booking_delete' => 'bookings#booking_delete',:as=>"delete"
      post '/notifications_settings'=>'users#notification_settings'
      get '/notifications_settings' => 'users#get_settings_of_notifications'
      devise_scope :user do
  		  post 'registrations' => 'registrations#create', :as => 'register'
        post 'facebook-callbacks' => 'registrations#facebook',:as=>'facebook-callbacks'
        post 'google-callbacks' => 'registrations#google_oauth2',:as=>'google-callbacks'
        post 'sessions' => 'sessions#create', :as => 'login'
  		  delete 'sessions' => 'sessions#destroy', :as => 'logout'
  	  end

    end
  end

end

app/controllers/api/v1/transactions_controller.rb
class Api::V1::TransactionsController <  Api::V1::BaseController

    include TransactionsHelper,HomeHelper
    before_action :authenticate_user!,:except => [:calculate_tax]
    before_action :check_booking, :only => [:create]
    before_action :auth_to_create!, :only => [:create,:new]

    def new
      client_token = Transaction.generate_client_token(current_user)
      render(json: { client_token:client_token }.to_json)

      # @transaction=Transaction.new
    end

    def calculate_tax

     amount=params[:service_amount]
     total_amount=(amount.to_i-((8.875/100)*amount.to_i)).round
     render(json: { service_amount:amount,taxable_amount:((8.875/100)*amount.to_i).round,total_amount:total_amount }.to_json)

    end

    def create

      transaction_params=params[:transaction]
      booking=Booking.find(transaction_params[:booking_id])
      pay_half_trans_and_full_gift=transaction_params[:pay_half_trans_and_full_gift].blank? ? false : true
      amount_plain_trans=transaction_params[:amount]
      gift_deducted_amount=transaction_params[:gift_deducted_amount]
      amount=gift_deducted_amount.blank? ?  amount_plain_trans : gift_deducted_amount
      @result=Transaction.transaction_sale(transaction_params,amount,false)
      if @result.success?

        transaction=Transaction.new(booking_id:booking.id,braintree_transaction_id:@result.transaction.id,stylist_id:booking.stylist_id,amount_paid:amount,transaction_status:@result.transaction.status,pay_via:"transaction")
        transaction.save
        booking.update(:status => Booking::PENDING)
        create_message_booking(params[:message], booking) if !params[:message].blank?

        Transaction.booking_success_with_successfull_transaction_message(current_user)

        RedderaWorker.perform_at(10.minute.from_now, booking.id, transaction.braintree_transaction_id) if booking.dates == Date.today
        RedderaWorker.perform_at(1.hour.from_now, booking.id, transaction.braintree_transaction_id) if booking.dates > Date.today
        current_user.update(braintree_customer_id: @result.transaction.customer_details.id) #unless current_user.has_payment_info?

        if pay_half_trans_and_full_gift == true
          gift_card=GiftCard.find(transaction_params[:gift_card_id])
          discounted_amount=transaction_params[:discounted_amount]
          update_gift_card(gift_card)
          transaction=Transaction.new(booking_id:booking.id,gift_card_id:gift_card.id,stylist_id:booking.stylist_id,pay_via:"pay_half_trans_and_gift",amount_paid:discounted_amount)
          transaction.save
        end
        render(json: { success: true, transaction_id:transaction.id,message: "Transaction successfully created." }.to_json)

      else
        #flash[:alert] = "Something went wrong while processing your transaction. Please try again!"
        gon.client_token =Transaction.generate_client_token(current_user)
        render(json: { success: false, message:@result.errors.map{|error| error.message}.join(" ")}.to_json)


      end



    end

    def gift_card_payment_create
      transaction=Transaction.new
      transaction.gift_card_id=params[:gift_card_id]
      gift_card= GiftCard.find(params[:gift_card_id])
      @result=Transaction.transaction_sale(params,params[:amount],true)
      if @result.success?
        transaction.braintree_transaction_id=@result.transaction.id
        transaction.transaction_status=@result.transaction.status
        transaction.save
        UserMailer.gift_card(gift_card).deliver
        render(json:{ success: true, message: "Transaction successfully created." }.to_json)
      else
        gon.client_token =Transaction.generate_client_token(current_user)
        render(json:{ success: false, message: @result.errors.map{|error| error.message}.join(" ")}.to_json)
      end
    end

    def pay_via_gift_card
     begin
      booking=Booking.find(params[:booking_id])
      Transaction.pay_via_gift_card_micro(params,booking)
      create_message_booking(params[:message], booking) if !params[:message].blank?
      render(json:{ success: true, message: "Transaction successfully created." }.to_json)
     rescue ActiveRecord::RecordNotFound
      not_found
    end
    end


    def discounted_price
      begin

        @service_amount=params[:service_amount]
        @total_amount=Transaction.total_amount_deducted_from_tax(@service_amount)
        @taxable_amount= format('%02d', ((8.875/100)*@service_amount.to_i).round)
        coupon=params[:coupon_code]
        raise Exception, "Enter the code" if  coupon.blank?
        @gift_card=GiftCard.find_by_gift_code(coupon)
        raise Exception, "Please enter a valid code"  if @gift_card.blank? || check_coupon_validity(@gift_card)
        gift_amount=Transaction.get_gift_amount(@gift_card)
        discounted_price_calculation(@total_amount,gift_amount)
        render(json:{ service_amount:@service_amount,total_amount:@total_amount,taxable_amount:@taxable_amount,json:@json,gift_card_id:@gift_card.id}.to_json)

          #render_transaction_bill_page

      rescue Exception => exc
        @message=exc.message
        render(json:{ success: false, message:@message }.to_json)


      end

    end

    def index
      @notify =params[:notify]

      if current_user.isStylist?
        #@payment_info= !PayoutInfo.find_by_user_id(current_user.id).blank? ? PayoutInfo.find_by_user_id(current_user.id) : PayoutInfo.new

        transactions=Transaction.transaction_history


        # transactions=Transaction.where(:stylist_id => current_user.id)
       getTransactionListJson(transactions)
      else
       transactions=Transaction.transaction_history
        # bookings=Booking.where(:user_id=>current_user.id)
        # transactions=bookings.map{|booking|booking.transactions.first}.reject{|n| n==nil}

       render(json:transactions,each_serializer: Api::V1::GroupedSomeModelSerializer)


      # getTransactionListJson(transactions)
      end
    end

    protected


    def getTransactionListJson(transactions)
      render(
          json:
              transactions,
              each_serializer: Api::V1::TransactionSerializer,


      )
    end

    def check_booking
      begin
        @booking = Booking.find(params[:transaction][:booking_id])
      rescue ActiveRecord::RecordNotFound
        not_found
      end
    end

    def auth_to_create!
      return (current_user.isClient?) ? true : unauthenticated!
    end

    def transaction_params
        params[:transaction].permit(:braintree_transaction_id ,:booking_id)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
 def get_amount_paid_for_tranaction(trans)
  sum=0
   if trans.size==1
   trans.first.amount_paid
   else
    trans.map(&:amount_paid).each{|amount| sum+=amount.to_i}
    return sum
   end
 end

 def discounted_price_calculation(total_amount,gift_amount)
  gift_deducted_amount=lambda{|a,b| a - b}

  if total_amount==gift_amount

   @pay_via_entire_gift=true
   gift_deducted_amount=gift_deducted_amount.call(total_amount,gift_amount)
   @json={gift_deducted_amount:gift_deducted_amount,gift_remaining_amount:gift_deducted_amount,discounted_amount:gift_amount,amount_to_be_payed:gift_amount,pay_via_entire_gift:true,pay_half_trans_and_full_gift:false,pay_half_from_gift:false}

  elsif total_amount > gift_amount

   @pay_half_trans_and_full_gift=true
   gift_deducted_amount=gift_deducted_amount.call(total_amount,gift_amount)
   @json={gift_deducted_amount:gift_deducted_amount,gift_remaining_amount:0,discounted_amount:gift_amount,amount_to_be_payed:gift_deducted_amount,pay_via_entire_gift:false,pay_half_trans_and_full_gift:true,pay_half_from_gift:false}

   session[:pay_half_trans_and_full_gift]=true
  else

   @pay_half_from_gift=true
   @gift_deducted_amount=gift_deducted_amount.call(gift_amount,total_amount)
   @json={gift_deducted_amount:0,gift_remaining_amount:@gift_deducted_amount,discounted_amount:@total_amount,amount_to_be_payed:@total_amount,pay_via_entire_gift:false,pay_half_trans_and_full_gift:false,pay_half_from_gift:true}
  end
 end

 def update_gift_card(gift_card)
  gift_card.remaining_amount=0
  gift_card.is_valid=false
  gift_card.save
 end

 def check_coupon_validity(gift_card)
  gift_card.is_valid == true ? false : true
 end
end

app/views/transactions/_billing_amount.html.erb
<%if !@message.blank?%>
    <div class="alert alert-success alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%=@message%>
    </div>
<%end%>


 <%#debugger%>

      <div class="pr2">
        <div class="subtotal-box"><span class="sub-total">Service Amount</span><span class="sub-total">$<%=@service_amount%></span></div>
        <div class="subtotal-box"> <span class="sub-total">Taxable Amount</span><span class="sub-total">$<%=@taxable_amount%></span> </div>
        <div class="subtotal-box">  <span class="sub-total-box bcb"><%=@gift_deducted_amount.nil? ? "Total" : "Sub-Total" %></span> <span class="sub-total">$<%=@total_amount%></span> </div>
        <%if !@json.blank?%>
        <div class="subtotal-box"><span class="sub-total">Discount</span><span class="sub-total"><%=@json[:discounted_amount]%></span></div>
          <div class="subtotal-box">
            <span class="sub-total-box bcb">Total</span> <span class="sub-total"><%=@json[:gift_deducted_amount]%></span>

          </div>
        <%end%>
        </div>
     <%if !@json.blank?%>
    <div class="alert alert-success alert-info pull-left" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      Amount remaining in gift card is $<%=@json[:gift_remaining_amount]%>
    </div>
    <%end%>

<%if !@json.blank?%>

<!--<button type="button" id="pay_via_gift" class="btn btn-close btn-primary pull-right mt30" style="display: none">Pay for service</button>-->

    <%= form_tag  pay_gift_card_path, :html => {:method => :post} do %>
        <%= hidden_field_tag "pay_via_entire_gift", @pay_via_entire_gift.blank? ? false:true %>
        <%= hidden_field_tag "pay_half_from_gift", @pay_half_from_gift.blank? ? false:true %>
        <%= hidden_field_tag "gift_card_id", @gift_card.id %>
        <%= hidden_field_tag "amount_to_be_payed", @json[:amount_to_be_payed] %>
        <%= hidden_field_tag "gift_amount", @json[:gift_amount] %>
        <%= hidden_field_tag "remaining_amount", @json[:gift_remaining_amount] %>

        <%= submit_tag "Pay for Service", class: "btn btn-close btn-primary pull-right mt30" ,:id=>"pay_via_gift", :stylist_id=>current_user.id,:style=>"margin-right:10px"%>

        <%#=button_to 'Pay for Service',pay_gift_card_path(@amount_to_be_payed,@gift_amount,@gift_card) ,:id=>"pay_via_gift",:class=>"btn btn-close btn-primary pull-right mt30",method: :post%>
   <%end%>
<%end%>
<script type="text/javascript">


</script>

app/views/transactions/_customer_form.html.erb
<div class="col-lg-12 col-sm-12 col-xs-12 text-center"> <span>
          <h2 class="sh7">Please enter your personal details</h2>
          </span>
</div>
<div class="row">

    <div class="col-xs-3">
      <%= text_field_tag :first_name, "",placeholder: "First Name", class: "form-control" ,:value=>current_user.first_name%>
    </div>

    <div class="col-xs-3">
      <%= text_field_tag :last_name, "",placeholder: "Last Name", class: "form-control" ,:value=>current_user.last_name%>
    </div>

    <div class="col-xs-3">
      <%= text_field_tag :phone, "",placeholder: "Phone", class: "form-control" ,:value=>current_user.phone%>
    </div>

</div>

app/views/transactions/index.html.erb
<div id="transactionhistory" class="tab-pane active">
<section class="container">
  <%if !@notify.blank?%>
      <div class="alert alert-success alert-danger" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%=@notify%>
      </div>
  <%end%>
 <%if current_user.isStylist?%>
  <div class="row transactions">
    <div>
      <div class="col-md-3 col-sm-3 col-xs-12">
        <div class="page-header">
          <h1 class="pull-left">
            Payout
            <br>
            Method
          </h1>

          <span class="pull-left msg-notf-icon">
                <img src="<%=asset_path('icon-payment.png')%>">
          </span>
          <div class="clearfix"></div>
          <h5>Edit or Add Payout Methods </h5>
         </div>

        </div>
      <div class="col-md-9 col-sm-9 col-xs-12">
        <div class="row">
          <div class="trs-ctn">
            When you receive a payment for a service, you’ll receive a payout.Our secure payment system supports several payout methods, which can be setup and altered here. Visit the
            <a href="#">Payout FAQ.</a>
          </div>
          <%= form_for @payment_info,:url=>user_payment_info_path(current_user.id)  , :method => :put do |f| %>
          <div class="form-row mt35">
            <div class="col-md-6">
              <div class="form-group">
                <label for="legal_name">Legal Name</label>
                <%= f.text_field :legal_name,  class: "form-control",:placeholder=>"Legal Name" %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label for="business_name">Business Name</label>
                <%= f.text_field  :business_name,  class: "form-control",:placeholder=>"Business Name" %>
              </div>
            </div>

          </div>

          <div class="form-row">
            <div class="col-md-4">
              <div class="form-group">
                <label for="tax_id">Tax ID</label>
                <%= f.text_field  :tax_id,  class: "form-control",:placeholder=>"Tax ID" %>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label for="dob">Date Of Birth</label>
                <%= f.text_field   :dob, class: "form-control",:placeholder=>"Date Of Birth" %>
              </div>
            </div>
              <div class="col-md-4">
                <div class="form-group">
                  <label for="ssn">SSN (Full or Last 4 Digits)</label>
                  <%= f.text_field   :ssn,  class: "form-control",:placeholder=>"SSN (Full or Last 4 Digits)" %>
                </div>
              </div>

              </div>
          <div class="form-row">
            <div class="col-md-6">
              <div class="form-group">
                <label for="account_number">Account Number</label>
                <%= f.number_field :account_number,  class: "form-control",:placeholder=>"Account Number" %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label for="routing_number">Routing Number</label>
                <%=  f.number_field :routing_number,class: "form-control",:placeholder=>"Routing Number" %>

              </div>
            </div>


          </div>
          <div class="form-row">
            <div class="col-md-12">
              <div class="form-group">
                <label for="street_address">Street Address</label>
                <%= f.text_field  :street_address, class: "form-control",:placeholder=>"Street Address" %>

              </div>
            </div>
          </div>

          <div class="form-row">
            <div class="col-md-4">
              <div class="form-group">
                <label for="city">City</label>
                <%= f.text_field  :city,  class: "form-control",:placeholder=>"City" %>

              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label for="state">State</label>
                <%=select_tag :state, options_for_select(us_states),class: "form-control" %>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label for="zip_code">Zip Code</label>
                <%= f.number_field :zipcode,  class: "form-control",:placeholder=>"Zip Code"%>
              </div>
            </div>
            <div class="form-row">
              <div class="col-md-6">
                <div class="form-group checkbox-outer">
                  <h6 class="terms-ctent">Braintree’s Terms</h6>
                  <div class="checkbox">
                    <input id="remember" class="" type="checkbox" name="remember" tabindex="3">
                    <label class="checkbox-text" for="remember"> I accept Braintree’s Terms and Conditions.</label>
                  </div>
                </div>
              </div>

              <div class="col-md-6 mt30">
                <span>
                  <%= submit_tag "Update", class: "btn-confirm btn btn-small btn-primary" %>

                </span>
              </div>
            </div>

          </div>

           <%end%>
            </div>
        </div>
        <div class="clearfix"></div>
      </div>
  </div>
  <%end%>

  <div class="row dashboard">
    <div class="col-md-3 col-sm-3 col-xs-12">

      <div class="page-header">
        <h1 class="pull-left">
          Recent
          <br>
          Transactions
        </h1>
        <span class="pull-left msg-notf-icon">
            <img src="<%=asset_path('icon-watch.png')%>">
        </span>

        <div class="clearfix"></div>
        <h5>View Recent Transactions </h5>
      </div>
    </div>
    <div class="col-md-9 col-sm-9 col-xs-12">
          <% @transactions.each do |transaction| %>


            <div class="table-responsive table-booking">

              <table class="table table-condensed latest-thum-size text-justfy">
                <tbody>
                <tr>
             <td>
                  <%if current_user.isStylist?%>

                            <a href="<%=client_path(transaction[0].user.id,transaction[0].user.first_name)%>" class="thumbnail  "><%=image_tag transaction[0].user.photo.image.url,:class=>"img-circle"%></a>
                        <%=  transaction[0] .user.first_name%>


                <%else%>
                        <a href="<%=stylist_path(transaction[0].stylist.id,transaction[0].stylist.first_name) %>" class="thumbnail  "><%= image_tag transaction[0].stylist.photo.image.url,:class=>"img-circle"%></a>
                      <%=  transaction[0].stylist.first_name%>

                  <%end%>
             </td>

                  <td>
                    <%= Booking.get_services_name_by_booking(transaction[0])%></td>
                  <td>
                    <%=transaction[0].dates.strftime("%a - %b. %d %Y") %>,<%= transaction[0].slots.slice(0,7) %></td>
              <td>$<%=  get_amount_paid_for_tranaction(transaction[1]) %></td>

           <td>
                  <%#= link_to "DELETE", transaction_path(transaction.id),:class=>"btn-confirm btn btn-small btn-primary" , method: :delete %>
         </td>


            <br/>

                  <%end%>
      </tr>
      </tbody>
      </table>
        </div>
      </div>
    </div>



</section>





    </div>
<script>
    $( document ).ready(function() {
        NProgress.done();

    });
</script>